export const olddevelopers = [
    {
        id: 1,
        fName: "Juozas",
        lName: "Petkevičius",
        email: "juozas.petkus@gmail.com",
        password: "",
        age: "69",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React"
    },
    {
        id: 2,
        fName: "Ramunė",
        lName: "Banienė",
        email: "ramune.ban@gmail.com",
        password: "",
        age: "49",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "Vue"  
    },
    {
        id: 3,
        fName: "Ignas",
        lName: "Softas",
        email: "ignas.soft@gmail.com",
        password: "",
        age: "21",
        gender: "Male",
        category: "Back-end",
        level: "Junior",
        framework: "Vue"  
    },
    {
        id: 4,
        fName: "Holly-anne",
        lName: "Knighton",
        email: "hknighton3@booking.com",
        password: "",
        age: "28",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React"
      },
      {
        id: 5,
        fName: "Sollie",
        lName: "Naulty",
        email: "snaulty4@hud.gov",
        password: "",
        age: "38",
        gender: "Male",
        category: "Back-end",
        level: "Junior",
        framework: "React"     , },
      {
        id: 6,
        fName: "Annie",
        lName: "Cockayme",
        email: "acockayme5@tuttocitta.it",
        password: "",
        age: "22",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React"
     , },
      {
        id: 7,
        fName: "Celinda",
        lName: "Sharvill",
        email: "csharvill6@narod.ru",
        password: "",
        age: "40",
        gender: "Female",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
    },
      {
        id: 8,
        fName: "Lamond",
        lName: "Ricket",
        email: "lricket7@washington.edu",
        age: "40",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
     , },
      {
        id: 9,
        fName: "Florida",
        lName: "Licciardiello",
        email: "flicciardiello8@sina.com.cn",
        age: "30",
        gender: "Female",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 10,
        fName: "Gerianne",
        lName: "Jonas",
        email: "gjonas9@typepad.com",
        age: "36",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 11,
        fName: "Amy",
        lName: "Tarbath",
        email: "atarbatha@t.co",
        age: "25",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 12,
        fName: "Jerrilyn",
        lName: "Devil",
        email: "jdevilb@upenn.edu",
        age: "55",
        gender: "Male",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 13,
        fName: "Derrik",
        lName: "Halvorsen",
        email: "dhalvorsenc@loc.gov",
        age: "51",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 14,
        fName: "Kellia",
        lName: "Driutti",
        email: "kdriuttid@skyrock.com",
        age: "29",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 15,
        fName: "Denys",
        lName: "Abrams",
        email: "dabramse@godaddy.com",
        age: "49",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 16,
        fName: "Sophie",
        lName: "Wadmore",
        email: "swadmoref@taobao.com",
        age: "24",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 17,
        fName: "Ivonne",
        lName: "Axby",
        email: "iaxbyg@paginegialle.it",
        age: "40",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 18,
        fName: "Andee",
        lName: "Babcock",
        email: "ababcockh@hubpages.com",
        age: "26",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 19,
        fName: "Shawn",
        lName: "Baxstair",
        email: "sbaxstairi@artisteer.com",
        age: "33",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 20,
        fName: "Randolph",
        lName: "Chowne",
        email: "rchownej@nymag.com",
        age: "41",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 21,
        fName: "Hayward",
        lName: "Emmet",
        email: "hemmetk@ustream.tv",
        age: "43",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 22,
        fName: "Paule",
        lName: "Kleinhausen",
        email: "pkleinhausenl@bigcartel.com",
        age: "21",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 23,
        fName: "Berton",
        lName: "Wingeatt",
        email: "bwingeattm@taobao.com",
        age: "60",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 24,
        fName: "Ameline",
        lName: "Jeanon",
        email: "ajeanonn@bandcamp.com",
        age: "22",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 25,
        fName: "Shepperd",
        lName: "Oertzen",
        email: "soertzeno@arstechnica.com",
        age: "31",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 26,
        fName: "Sean",
        lName: "Veltmann",
        "email": "sveltmannp@jigsy.com",
        age: "35",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 27,
        fName: "Julie",
        lName: "Pigot",
        email: "jpigotq@archive.org",
        age: "28",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 28,
        fName: "Goldi",
        lName: "Tink",
        email: "gtinkr@tripod.com",
        age: "56",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
     , },
      {
        id: 29,
        fName: "Jeannie",
        lName: "Kennelly",
        email: "jkennellys@hugedomains.com",
        age: "30",
        gender: "Female",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
     , },
      {
        id: 30,
        fName: "Josephine",
        lName: "Kennefick",
        email: "jkennefickt@icq.com",
        age: "44",
        gender: "Female",
        category: "Back-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 31,
        fName: "Elli",
        lName: "Pettigrew",
        email: "epettigrewu@nsw.gov.au",
        age: "45",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
      },
      {
        id: 32,
        fName: "Nevins",
        lName: "McGlaughn",
        email: "nmcglaughnv@webnode.com",
        age: "34",
        gender: "Maale",
        category: "Back-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 33,
        fName: "Roseann",
        lName: "Schwant",
        email: "rschwantw@bandcamp.com",
        age: "26",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
      },
      {
        "id": 34,
        fName: "Hunt",
        lName: "McGaughay",
        email: "hmcgaughayx@freewebs.com",
        age: "64",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 35,
        fName: "Inger",
        lName: "Sussans",
        email: "isussansy@webnode.com",
        age: "19",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 36,
        fName: "Hobie",
        lName: "Rodman",
        email: "hrodmanz@oakley.com",
        age: "18",
        gender: "Male",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
      },
      {
        id: 37,
        fName: "Shandra",
        lName: "Creighton",
        email: "screighton10@storify.com",
        age: "32",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
      },
      {
        id: 38,
        fName: "Poppy",
        lName: "Benne",
        email: "pbenne11@ameblo.jp",
        age: "20",
        gender: "Male",
        category: "Back-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 39,
        fName: "Skelly",
        lName: "Critchard",
        email: "scritchard12@slate.com",
        age: "27",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 40,
        fName: "Rhea",
        lName: "Purple",
        email: "rpurple13@admin.ch",
        age: "19",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 41,
        fName: "Gilberto",
        lName: "Tift",
        email: "gtift14@simplemachines.org",
        age: "29",
        gender: "Male",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 42,
        fName: "Celinka",
        lName: "Nolleau",
        email: "cnolleau15@etsy.com",
        age: "39",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 43,
        fName: "Sascha",
        lName: "McKevitt",
        email: "smckevitt16@jigsy.com",
        age: "40",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 44,
        fName: "Blondelle",
        lName: "Mussalli",
        email: "bmussalli17@wiley.com",
        age: "26",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 45,
        fName: "Gal",
        lName: "Corkell",
        email: "gcorkell18@freewebs.com",
        age: "19",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 46,
        fName: "Renaldo",
        lName: "Letch",
        email: "rletch19@dyndns.org",
        age: "27",
        gender: "Male",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 47,
        fName: "Marian",
        lName: "Scally",
        email: "mscally1a@bbc.co.uk",
        age: "18",
        gender: "Male",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
      },
      {
        id: 48,
        fName: "Jenine",
        lName: "Quilliam",
        email: "jquilliam1b@youtu.be",
        age: "33",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 49,
        fName: "Kit",
        lName: "Strahan",
        email: "kstrahan1c@ovh.net",
        age: "59",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 50,
        fName: "D'arcy",
        lName: "Normanville",
        email: "dnormanville1d@xinhuanet.com",
        age: "40",
        gender: "Female",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
      },
    ];