export const olddevelopers = [
    {
        id: 1,
        fName: "Juozas",
        lName: "Petkevičius",
        email: "juozas.petkus@gmail.com",
        password: "",
        age: "69",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React"
    },
    {
        id: 2,
        fName: "Ramunė",
        lName: "Banienė",
        email: "ramune.ban@gmail.com",
        password: "",
        age: "49",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "Vue"  
    },
    {
        id: 3,
        fName: "Ignas",
        lName: "Softas",
        email: "ignas.soft@gmail.com",
        password: "",
        age: "21",
        gender: "Male",
        category: "Back-end",
        level: "Junior",
        framework: "Vue"  
    },
    {
        id: 4,
        fName: "Holly-anne",
        lName: "Knighton",
        email: "hknighton3@booking.com",
        password: "",
        age: "28",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React"
      },
      {
        id: 5,
        fName: "Sollie",
        lName: "Naulty",
        email: "snaulty4@hud.gov",
        password: "",
        age: "38",
        gender: "Male",
        category: "Back-end",
        level: "Junior",
        framework: "React"     , },
      {
        id: 6,
        fName: "Annie",
        lName: "Cockayme",
        email: "acockayme5@tuttocitta.it",
        password: "",
        age: "22",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React"
     , },
      {
        id: 7,
        fName: "Celinda",
        lName: "Sharvill",
        email: "csharvill6@narod.ru",
        password: "",
        age: "40",
        gender: "Female",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
    },
      {
        id: 8,
        fName: "Lamond",
        lName: "Ricket",
        email: "lricket7@washington.edu",
        age: "40",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
     , },
      {
        id: 9,
        fName: "Florida",
        lName: "Licciardiello",
        email: "flicciardiello8@sina.com.cn",
        age: "30",
        gender: "Female",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 10,
        fName: "Gerianne",
        lName: "Jonas",
        email: "gjonas9@typepad.com",
        age: "36",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 11,
        fName: "Amy",
        lName: "Tarbath",
        email: "atarbatha@t.co",
        age: "25",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 12,
        fName: "Jerrilyn",
        lName: "Devil",
        email: "jdevilb@upenn.edu",
        age: "55",
        gender: "Male",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 13,
        fName: "Derrik",
        lName: "Halvorsen",
        email: "dhalvorsenc@loc.gov",
        age: "51",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 14,
        fName: "Kellia",
        lName: "Driutti",
        email: "kdriuttid@skyrock.com",
        age: "29",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 15,
        fName: "Denys",
        lName: "Abrams",
        email: "dabramse@godaddy.com",
        age: "49",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 16,
        fName: "Sophie",
        lName: "Wadmore",
        email: "swadmoref@taobao.com",
        age: "24",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 17,
        fName: "Ivonne",
        lName: "Axby",
        email: "iaxbyg@paginegialle.it",
        age: "40",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 18,
        fName: "Andee",
        lName: "Babcock",
        email: "ababcockh@hubpages.com",
        age: "26",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 19,
        fName: "Shawn",
        lName: "Baxstair",
        email: "sbaxstairi@artisteer.com",
        age: "33",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 20,
        fName: "Randolph",
        lName: "Chowne",
        email: "rchownej@nymag.com",
        age: "41",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 21,
        fName: "Hayward",
        lName: "Emmet",
        email: "hemmetk@ustream.tv",
        age: "43",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "React" 
      },
      {
        id: 22,
        fName: "Paule",
        lName: "Kleinhausen",
        email: "pkleinhausenl@bigcartel.com",
        age: "21",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
     , },
      {
        id: 23,
        fName: "Berton",
        lName: "Wingeatt",
        email: "bwingeattm@taobao.com",
        age: "60",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
      },
      {
        id: 24,
        fName: "Ameline",
        lName: "Jeanon",
        email: "ajeanonn@bandcamp.com",
        age: "22",
        gender: "Female",
        category: "Front-end",
        level: "Junior",
        framework: "React" 
      },
      {
        id: 25,
        fName: "Shepperd",
        lName: "Oertzen",
        email: "soertzeno@arstechnica.com",
        age: "31",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 26,
        fName: "Sean",
        lName: "Veltmann",
        "email": "sveltmannp@jigsy.com",
        age: "35",
        gender: "Male",
        category: "Back-end",
        level: "Senior",
        framework: "React" 
     , },
      {
        id: 27,
        fName: "Julie",
        lName: "Pigot",
        email: "jpigotq@archive.org",
        age: "28",
        gender: "Female",
        category: "Back-end",
        level: "Junior",
        framework: "Vue" 
     , },
      {
        id: 28,
        fName: "Goldi",
        lName: "Tink",
        email: "gtinkr@tripod.com",
        age: "56",
        gender: "Male",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
     , },
      {
        id: 29,
        fName: "Jeannie",
        lName: "Kennelly",
        email: "jkennellys@hugedomains.com",
        age: "30",
        gender: "Female",
        category: "Front-end",
        level: "Senior",
        framework: "Vue" 
     , },
      {
        id: 30,
        fName: "Josephine",
        lName: "Kennefick",
        email: "jkennefickt@icq.com",
        age: "44",
        gender: "Female",
        category: "Back-end",
        level: "Senior",
        framework: "Vue" 
      },
    ];